### ISSUE TITLE
PCB missing

### ISSUE THREAD

**Issue by MaltWhiskey** [sanderdh/FilamentClock#1]
Hello Sander,

This is a very nice creation, i would very much like to have a look at your pcb design to learn and maybe create something similar for my home. Would you be willing to put your pcb design in your repo?

Thank you.

PS:
Je kan me ook een bericht sturen naar mijn naam die ik gebruik @outlook.com (ff de vieze spammers misleiden). Het is puur voor mezelf, ik heb nogal een ledjes fetish en jou creatie pas perfect in mijn straatje :P (zie mijn dingen op mijn youtube of github)

**Comment by sanderdh** [comment]
Hi, thanks for your interest. The current design contains some mistakes that I fixed using bodges (mostly hidden on the back of the pcb), so I am not releasing the design. I can sent you a pcb with components and the fixes applied. You would have to solder the brass wires and filaments yourself. Contact me if interested.
